### ISSUE TITLE
Getting  error  message  when  hitting  C-c  C-c  on  ...

### ISSUE THREAD

**Issue by michaelsjackson** [sachac/sachac.github.io#1]
`#+CALL: graph-from-tables[](fillcolumn=20,include-someday=1,outputfile="someday.svg",cmdline="-Kdot -Tsvg -Gdpi=72 -Gsize=10,10 -Grankdir=LR") :results silent :exports none`

Just wanted  to  try  quickly  index.org, but  without  any  success.  Thanks  for  sharing.  I  am  using  emacs-25.3

**Comment by sachac** [comment]
You might have more luck with https://github.com/the-humanities/org-mind-map , maybe? Mine still works with M-x org-babel-execute-buffer, but I don't have the brainspace or computer time to dig further at the moment. Good luck!

**Comment by sachac** [comment]
Oh, and you may want to try with a newer version of Emacs and Org, too!

**Comment by michaelsjackson** [comment]
Dear Sacha, did not expect you to answer, but you did, thanks a lot. org-mind-map I know and using already. Actually anything related to org-brain, mind-map, graph kind of stuff I am already using, at least what works in emacs-25.3, I tried updating a few months back to latest emacs, but got lots of error with other stuff I need every day, mainly using org-mode and creating pdf documents, so thought emacs update can wait. I am wondering why an emacs update can not work, without destroying stuff which were working previously. It is then like getting +2 new features but -50 features, which I need daily, so I prefer keeping those 50 important features, with the older emacs.

It is good to know your code is not compatible with emacs-25.3, thanks again.  One day, when I update emacs successfully, I can try again, then reporting back here.  Mainly I liked the style of your graph more than what org-mind-map is giving, the top header is on the right, which would be perfect for a lecture context, the main goal would stay on the right side, from left we could see which paths we will take to reach the goal.

But there are a few quite interesting graphing solutions in the last weeks. Probably you know them all as well, org-graph-view, org-zettelkasten*, obr-viz**


* https://github.com/l3kn/org-zettelkasten
** https://github.com/swhalemwo/obr-viz/

**Comment by michaelsjackson** [comment]
> You might have more luck with https://github.com/the-humanities/org-mind-map , maybe? Mine still works with M-x org-babel-execute-buffer, but I don't have the brainspace or computer time to dig further at the moment. Good luck!


You do not need to answer, just for completeness, I am posting the error message I am getting, with my emacs-25.3

> Debugger entered--Lisp error: (void-function org-babel-execute:dot)
>   (org-babel-execute:dot (sacha/org-map-to-graphviz (sacha/org-map-goals tag) fill-column id) (list (cons :file outputfile) (cons :cmdline cmdline)))
>

**Comment by sachac** [comment]
Oh! Did you enable dot as one of org-babel-load-languages ?
https://orgmode.org/worg/org-contrib/babel/languages.html#configure

**Comment by michaelsjackson** [comment]
Dear Sacha, great tip, it works! Thanks million times!  Somehow I had the line with dot . t but it was commented out, probably in the past I had some errors there, my solution was to disable it probably, never looked again, now with your hint, the graphs are generated freshly now.

Now I have to play a bit, how I can use it bestly.  I guess if I would add your functions into my .emacs I could use those functions without including them each time into the .org file, that would be more comfortable.  Not sure why you use it differently, probably you are changing each time something?  If you wrote any blog post how to use these bestly, I would like to read them, now where everything is working, yuppie yeaaah, thanks again!

**Comment by sachac** [comment]
I'm pleasantly surprised that works. Hooray!

I put the code in my evil plans file so that people don't have to
cross-reference it with my config. The proper thing to do would be to
package it or contribute it to an existing package, but that will probably
have to wait until A- goes to school. Until then, at least you have
something to experiment with. Enjoy!

**Comment by michaelsjackson** [comment]
Yes, thanks, unfortunately it seems your elips codes too far to the border area, I had constant crashes of entire emacs-25.3, I never had such crashes, because I never used such advanced features, so using this is kind of risky. It seems only links are represented as arrows in your design, so not like org-mind-map, also not like org-brain, which is actually great, we have now 3 different styles of generating mind-maps, if emacs would not crash that would be perfect, but no problem, at least I can play around a bit. Thanks again, have a nice day!
